name: test-integration

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.4'
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: Test
        run: vendor/bin/phpunit --testsuite=Integration
        env:
          GOOGLE_SERVICE_ENABLED: true
          GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION }}
